'''
Problem: How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''

from collections import Counter

ls=[]
for i in range(2,101):
	for j in range(2,101):
		ls.append(i**j)

ans = len(Counter(ls).keys())
print(ans)
